name: Generate KiCad Schematic PDFs and Images

on: 
  push:
    branches:
      - main

jobs:
  checkout_generate_push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install KiCad
      run: |
        sudo add-apt-repository ppa:kicad/kicad-8.0-releases
        sudo apt update
        sudo apt install -y kicad poppler-utils

    - name: Generate schematics
      run: |
        chmod +x .github/scripts/generate_kicad_schematics.sh
        ./.github/scripts/generate_kicad_schematics.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
        git push