name: Generate KiCad Schematic PDFs and Images

on: push

jobs:
  generate_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:kicad/kicad-8.0-releases
        sudo apt update
        sudo apt install kicad
        sudo apt install -y kicad poppler-utils 

    - name: Run script
      run: |
        chmod +x .github/scripts/generate_kicad_schematics.sh
        .github/scripts/generate_kicad_schematics.sh

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Add generated schematic PDF"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
