name: Generate KiCad Schematic PDFs and Images

on: 
  push:
    branches:
      - main

jobs:
  checkout_generate_push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install KiCad
      run: |
        sudo add-apt-repository ppa:kicad/kicad-8.0-releases
        sudo apt update
        sudo apt install -y kicad poppler-utils

    - name: Generate schematics
      run: |
        chmod +x .github/scripts/generate_kicad_schematics.sh
        .github/scripts/generate_kicad_schematics.sh

    - name: Check if there are changes
      id: git_changes
      run: |
        git add .
        if git diff --cached --quiet; then
          echo "No changes detected" 
          echo "changes=false" >> $GITHUB_ENV
        else
          echo "Changes detected"
          echo "changes=true" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.changes == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "Automated commit from GitHub Actions"
        git push
