name: Generate KiCad Schematic PDFs and Images

on: 
  push:
    branches:
      - main

jobs:
  checkout_generate_push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache KiCad dependencies
      id: cache-kicad
      uses: actions/cache@v4
      with:
        path: /usr/bin/kicad-cli
        key: kicad-${{ runner.os }}-8.0

    - name: Install KiCad
      if: steps.cache-kicad.outputs.cache-hit != 'true'
      run: |
        sudo add-apt-repository ppa:kicad/kicad-8.0-releases
        sudo apt update
        sudo apt install -y kicad poppler-utils

    - name: Generate schematics
      run: |
        kicad-cli sch export pdf -n --output boards/bidirectional_load_switch/schematic.pdf boards/bidirectional_load_switch/pcb/bidirectional_load_switch.kicad_sch

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
        git push
